# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsentry < Formula
  desc "Watches Teleport AI session summaries and locks high-risk users"
  homepage "https://github.com/jsabo/tsentry"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsabo/tsentry/releases/download/v0.2.0/tsentry_0.2.0_darwin_amd64.tar.gz"
      sha256 "92e88d16f54dc57fad5de0f86ceac9937b0f08cc0525c0f6973f32458456de0f"

      define_method(:install) do
        bin.install "tsentry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsabo/tsentry/releases/download/v0.2.0/tsentry_0.2.0_darwin_arm64.tar.gz"
      sha256 "dd809ff7fdc00eedd94075e59c58f6489d3551d0dc03f9805415566f0c7df435"

      define_method(:install) do
        bin.install "tsentry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsabo/tsentry/releases/download/v0.2.0/tsentry_0.2.0_linux_amd64.tar.gz"
      sha256 "990e88b6a79daa310298a276079c4de6e957416bf00075c51a391a61b954de9a"
      define_method(:install) do
        bin.install "tsentry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsabo/tsentry/releases/download/v0.2.0/tsentry_0.2.0_linux_arm64.tar.gz"
      sha256 "7cecb7798bb3eaeed07540321873f75864b09647e9d5d8b7cc64e7467f4cb18e"
      define_method(:install) do
        bin.install "tsentry"
      end
    end
  end

  test do
    system "#{bin}/tsentry", "--version"
  end
end
