# This file was generated by GoReleaser. DO NOT EDIT.
cask "troles" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "82f6ed12c70e1ded9040fb083411bd9eb19bf47b57ae184d36bbd217cf16dcf5"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c1cd5ae87e0389b59d2defca4c10b76e7db703f0a35dc752e0bd903e3e7604e"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e12f5a2bae08c37999a9f2b37466677d80e918b069c521d8fe80697264f3ee6"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f2924f827cadab262e82e4b0ccbb57411e79af7a339668ec9935141187565e59"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_linux_arm64.tar.gz"
    end
  end

  name "troles"
  desc "Show a Teleport user's effective roles, including access-list grants"
  homepage "https://github.com/jsabo/troles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "troles"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/troles"]
    end
  end

  # No zap stanza required

end
