# This file was generated by GoReleaser. DO NOT EDIT.
cask "troles" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "41dca5ce8e7509bfcf7c487515b4fc3edbeeca901d222b24f41301375428334a"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffbb32f984e55c281980dc2366d186a6a6934e449886754c82e5e3d588467566"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9b797da281e1d041e23816b38e55bd6fd5b7d6ece71e04e7184bce107fabb9c6"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4fad9578352559ae437f0ba8117d133afb5e56454f48a45206e9c396fc343a3a"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_linux_arm64.tar.gz"
    end
  end

  name "troles"
  desc "Show a Teleport user's effective roles, including access-list grants"
  homepage "https://github.com/jsabo/troles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "troles"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/troles"]
    end
  end

  # No zap stanza required

end
