# This file was generated by GoReleaser. DO NOT EDIT.
cask "troles" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "f197d49ff41513eaba784c05c16d02bc926c58632fa46988a26fd9c876893d22"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b176bd693f48cb30f59435f8c9f2b16421e670b461693b9614e52d9abcbaca58"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "54088861027b38da90f931ffd5d67e869a7b8eb153986fd13690c5cd60032bfb"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "89efa81c8447fad543dd2a887519294cb88a6a9f235602b978d88b478ea88a86"
      url "https://github.com/jsabo/troles/releases/download/v#{version}/troles_#{version}_linux_arm64.tar.gz"
    end
  end

  name "troles"
  desc "Show a Teleport user's effective roles, including access-list grants"
  homepage "https://github.com/jsabo/troles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "troles"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/troles"]
    end
  end

  # No zap stanza required

end
