# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsentry" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "ced5629f0c20045750696c1fe35fae5084f663fca4dabc49be4f2405f21e5340"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5cdfe88d9e2025885513f6fe63d81e09778f081ccba52e9ff21b9b76c8582005"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "684b7d5df4aac54390ffff116004ecc4e53c664a69c259063ddfd83293b5d804"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4eede26f98ae57092b00069fd00e9244551882b717a292a284de58f9379e9ed8"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tsentry"
  desc "Watches Teleport AI session summaries and locks high-risk users"
  homepage "https://github.com/jsabo/tsentry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsentry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsentry"]
    end
  end

  # No zap stanza required

end
