# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsentry" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "6c6208dda0e1f0b1ea4567af52848682dacecae41af293922597b3cb6e1c2498"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "14cf5f8ad183d5d9ba29bc7fa56404e330e7258f92410735f0f17d27a66d479e"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "925e6e9770fc61ba85465a3acba5f4398150eed7c2aed99dae2066c8be0aae8b"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f5a47a6f0701d1de2a2f09c54a49abb050a14c1428194aace59f9e4b4d4f0596"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tsentry"
  desc "Watches Teleport AI session summaries and locks high-risk users"
  homepage "https://github.com/jsabo/tsentry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsentry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsentry"]
    end
  end

  # No zap stanza required

end
