# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsentry" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "cb812234b33d3c6bacc74b49695ba71d39885d6590c6cd98ebe79b0c4786ad2e"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9282cdf6beff1e4810e6974735435c2cb139063eb14687298ef7dba8c5e6b99d"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "27c3c42ba770586e7c668b7638c9bbebf93d368eb23ce1770b63919612c263e6"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f02407e7bcd76a6a02f3d104d5d36de43f81689379d96fd174a0569658be6e2"
      url "https://github.com/jsabo/tsentry/releases/download/v#{version}/tsentry_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tsentry"
  desc "Watches Teleport AI session summaries and locks high-risk users"
  homepage "https://github.com/jsabo/tsentry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsentry"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsentry"]
    end
  end

  # No zap stanza required

end
